openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Simple contact book app with opportunity to create personal contacts.
    It has registration to customize contacts for different users.
tags:
  - name: Contacts
    description: Endpoints for managing contacts.
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-02nl.onrender.com
paths:
  /contacts:
    get:
      $ref: '../src/swagger/paths/contacts/get.yaml'
    post:
      $ref: '../src/swagger/paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: '../src/swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../src/swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../src/swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      $ref: '../src/swagger/components/schemas/contact.yaml'
